# Generated by Django 5.1.6 on 2025-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_creditrequest_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
